### ISSUE TITLE
Suggestion: SafetyNet

### ISSUE THREAD

**Issue by petrbel** [zhangqianhui/AdversarialNetsPapers#15]
Recently an interesting paper came out - [SafetyNet: Detecting and Rejecting Adversarial Examples Robustly](https://arxiv.org/abs/1704.00103) - which handles adversarial examples detections. It also contains other interesting related work.

I am not sure in which category to put it, hence I create an issue instead of PR. Sorry.

**Comment by zhangqianhui** [comment]
You can create a category called "Adversarial Examples" and put it.
Thanks for your PR!

**Comment by WuTheFWasThat** [comment]
do adversarial examples actually have much to do with adversarial networks though?
