### ISSUE TITLE
Would you please add DualGAN to the unsupervised GAN list

### ISSUE THREAD

**Issue by duxingren14** [zhangqianhui/AdversarialNetsPapers#18]
https://arxiv.org/abs/1704.02510
 DualGAN: Unsupervised Dual Learning for Image-to-Image Translation

Thanks,

**Comment by zhangqianhui** [comment]
ok,You can make a PR

**Comment by duxingren14** [comment]
Thanks. I am doing RPR. Just incidentally visited your wiki and saw
DiscoGAN, CycleGAN, but no DualGAN.
Actually, we are concurrent work. I would appreciate it if you list our
paper. Anyway, I will not push you if you feel inconvenient to do so.

**Comment by developershutt** [comment]
I've made PR #46.
