### ISSUE TITLE
Could you please add a more earlier segmantation work?

### ISSUE THREAD

**Issue by wentaozhu** [zhangqianhui/AdversarialNetsPapers#19]
Hi Qianhui,

I graduated from Shandong University.

Could you please add a early paper for segmentation "Adversarial Deep Structural Networks for Mammographic Mass Segmentation" https://arxiv.org/abs/1612.05970, code https://github.com/wentaozhu/adversarial-deep-structural-networks.git . It appears in the arXiv on last year, which is early than the NIPS workshop paper.

I am very appreciate if you could update your paper list.

Thanks very much!
Wentao

**Comment by zhangqianhui** [comment]
ok.You can make a PR.

**Comment by wentaozhu** [comment]
QIanhui,

Thanks a lot! I have done a PR. Please check and merge it.

Thanks a lot!
Wentao
