### ISSUE TITLE
2016 NIPS workshop has many new advances

### ISSUE THREAD

**Issue by fxia22** [zhangqianhui/AdversarialNetsPapers#2]
https://sites.google.com/site/nips2016adversarial/
https://sites.google.com/site/nips2016adversarial/home/accepted-papers

**Comment by zhangqianhui** [comment]
OK

**Comment by zhangqianhui** [comment]
can you pull request some paper ?

**Comment by fxia22** [comment]
Sure, I will add those w/ code.
