### ISSUE TITLE
The paper and code link for improved wgan seems wrong?

### ISSUE THREAD

**Issue by GaryLMS** [zhangqianhui/AdversarialNetsPapers#21]
The paper link is loss-sensitive gan, and the code link is improved wgan paper.

**Comment by zhangqianhui** [comment]
loss-sensitve ?

**Comment by GaryLMS** [comment]
Oh.. I misread the paper title.
And the Improved wgan paper code link should be this?
https://arxiv.org/abs/1704.00028

**Comment by zhangqianhui** [comment]
thanks!
