### ISSUE TITLE
Adversarial Training Methods for Semi-Supervised Text Classification  Is not about GANs!

### ISSUE THREAD

**Issue by nlml** [zhangqianhui/AdversarialNetsPapers#26]

**Comment by wentaozhu** [comment]
Adversarial example uses the discriminator to generate the data samples. From this point of view, it is GAN. And there are many work this year on computer vision using adversarial examples for segmentation, detection. One of our paper firstly uses the adversarial example for the image segmentation. If you are interested in, please read https://arxiv.org/abs/1612.05970 . Code is also available https://github.com/wentaozhu/adversarial-deep-structural-networks .
