### ISSUE TITLE
Image denoising or Image debluring with GAN?

### ISSUE THREAD

**Issue by lyatdawn** [zhangqianhui/AdversarialNetsPapers#29]
Hello,
Are there some Image denoising or Image debluring with GAN articles?
Thanks.

**Comment by wentaozhu** [comment]
I think you can use the adversarial segmentation related methods for image denoising.

**Comment by lyatdawn** [comment]
There are some methods like CNN or Autoencoder in Image denoising or Image debluring, Our teacher let me do some demos in Image denoising or Image debluring with GAN. 
Could you inform if there  are articles? 
Thanks!

**Comment by zhangqianhui** [comment]
About  image debluring, you can see the paper about image super-resolution methods[1]
About image denoising, you can the related paper about image de-rain method[2].Of course, this paper do not use the GAN architecture.

Hope to help you!
[1]Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network
[2]Removing rain from single images via a deep detail network

**Comment by lyatdawn** [comment]
Thanks, it's very useful !'
