### ISSUE TITLE
Face Aging With Conditional Generative Adversarial Networks

### ISSUE THREAD

**Issue by lyatdawn** [zhangqianhui/AdversarialNetsPapers#34]
Have this paper: "Face Aging With Conditional Generative Adversarial Networks" implement? 
I find in net for a long time, but no working.
Thanks

**Comment by zhangqianhui** [comment]
this paper is very easy to implement. 
You can imitate the image-to-image translation architecture to implement this paper.

**Comment by zhangqianhui** [comment]
for example, pix2pixe, cyclegan, stargan and so on.

**Comment by lyatdawn** [comment]
But this implement is used conditional GAN, not standard GAN.
Is right? In test phase, I want input a image and age, The net output the change aged image

**Comment by zhangqianhui** [comment]
Yeah, so, it can be implemented by stargan for multi-domain translation.
